// contact-manager-react/contact-frontend-vue/src/components/Login.vue
<template>
  <form @submit.prevent="handleLogin">
    <h2>Login</h2>

    <div>
      <label>Email:</label>
      <input v-model="form.email" type="email" required />
    </div>

    <div>
      <label>Password:</label>
      <input v-model="form.password" type="password" required />
    </div>

    <button type="submit">Login</button>
    <p v-if="message">{{ message }}</p>
  </form>
</template>

<script setup>
import { reactive, ref } from 'vue'
import axios from 'axios'

const form = reactive({
  email: '',
  password: ''
})

const message = ref('')

const handleLogin = async () => {
  try {
    const res = await axios.post('http://localhost:5000/login', form)
    message.value = res.data.message || 'Login successful!'
    // optionally store token here if backend returns one
  } catch (err) {
    message.value = err.response?.data?.message || 'Login failed.'
  }
}
</script>

<style scoped>
form {
  max-width: 400px;
  margin: 20px auto;
  padding: 15px;
  border: 1px solid #ccc;
  border-radius: 10px;
}
div {
  margin-bottom: 10px;
}
label {
  display: block;
}
input {
  width: 100%;
  padding: 8px;
}
</style>

// contact-management-react/src/components/Login.jsx
// src/components/Login.jsx
import React, { useState } from 'react'
import axios from 'axios'

const Login = () => {
  const [formData, setFormData] = useState({
    email: '',
    password: ''
  })
  const [message, setMessage] = useState('')

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value })
  }

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const res = await axios.post('http://localhost:5000/login', formData);
      console.log(res.data);  // Check what backend sends
  
      if (res.data.message === 'Login successful' && res.data.user_id) {
        localStorage.setItem('user_id', res.data.user_id);  // ✅ Store user_id
        setMessage('Login successful!');
      } else {
        setMessage('Login failed: Invalid credentials');
      }
    } catch (err) {
      setMessage('Login failed');
      console.error('Login error:', err);
    }
  };

  return (
    <div>
      <h2>Login</h2>
      <form onSubmit={handleSubmit}>
        <input
          name="email"
          type="email"
          placeholder="Email"
          onChange={handleChange}
          required
        />
        <input
          name="password"
          type="password"
          placeholder="Password"
          onChange={handleChange}
          required
        />
        <button type="submit">Login</button>
      </form>
      <p>{message}</p>
    </div>
  )
}

export default Login
