// contact-manager-react/contact-frontend-vue/src/components/Register.vue
<template>
  <form @submit.prevent="handleSubmit">
    <h2>Register</h2>

    <div>
      <label>Name:</label>
      <input v-model="form.name" required />
    </div>

    <div>
      <label>Email:</label>
      <input type="email" v-model="form.email" required />
    </div>

    <div>
      <label>Password:</label>
      <input type="password" v-model="form.password" required />
    </div>

    <button type="submit">Register</button>
    <p v-if="message">{{ message }}</p>
  </form>
</template>

<script setup>
import { reactive, ref } from 'vue'
import axios from 'axios'

const form = reactive({
  name: '',
  email: '',
  password: ''
})

const message = ref('')

const handleSubmit = async () => {
  try {
    const res = await axios.post('http://localhost:5000/register', form)
    message.value = res.data.message || 'Registered successfully!'
  } catch (err) {
    message.value = err.response?.data?.message || 'Registration failed.'
  }
}
</script>

<style scoped>
form {
  max-width: 400px;
  margin: 20px auto;
  padding: 15px;
  border: 1px solid #ccc;
  border-radius: 10px;
}
div {
  margin-bottom: 10px;
}
label {
  display: block;
}
input {
  width: 100%;
  padding: 8px;
}
</style>

// contact-management-react/src/components/Register.jsx
import React, { useState } from 'react';
import axios from 'axios';

function Register() {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: ''
  });

  const [message, setMessage] = useState('');

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const res = await axios.post('http://localhost:5000/register', formData, {
        headers: { 'Content-Type': 'application/json' }
      });
      setMessage(res.data.message || 'Registered successfully!');
    } catch (err) {
      console.error(err);
      setMessage('Registration failed');
    }
  };

  return (
    <div>
      <h2>Register</h2>
      <form onSubmit={handleSubmit}>
        <input name="name" placeholder="Name" onChange={handleChange} required />
        <input name="email" type="email" placeholder="Email" onChange={handleChange} required />
        <input name="password" type="password" placeholder="Password" onChange={handleChange} required />
        <button type="submit">Register</button>
      </form>
      <p>{message}</p>
    </div>
  );
}

export default Register;
