// contact-management-react/src/components/ContactList.jsx
import React, { useEffect, useState } from 'react';
import axios from 'axios';

function ContactList() {
  const [contacts, setContacts] = useState([]);
  const user_id = localStorage.getItem('user_id');

  useEffect(() => {
    const fetchContacts = async () => {
      try {
        const res = await axios.get(`http://localhost:5000/contacts?user_id=${user_id}`);
        setContacts(res.data);
      } catch (err) {
        console.error('Failed to fetch contacts:', err);
      }
    };

    if (user_id) fetchContacts();
  }, [user_id]);

  const handleDelete = async (id) => {
    try {
      await axios.delete(`http://localhost:5000/contacts/${id}`);
      setContacts(prev => prev.filter(contact => contact.id !== id));
    } catch (err) {
      console.error('Failed to delete contact:', err);
    }
  };

  return (
    <div>
      <h2>Your Contacts</h2>
      <ul>
        {contacts.map(contact => (
          <li key={contact.id}>
            {contact.name} - {contact.phone} - {contact.email}
            <button onClick={() => handleDelete(contact.id)}>Delete</button>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default ContactList;

// contact-manager-react/contact-frontend-vue/src/components/ContactList.vue
<template>
  <div>
    <h2>Contact List</h2>
    <div v-if="loading">Loading contacts...</div>
    <div v-else-if="error">{{ error }}</div>
    <table v-if="contacts.length">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="contact in contacts" :key="contact.id">
          <td>{{ contact.name }}</td>
          <td>{{ contact.email }}</td>
          <td>{{ contact.phone }}</td>
        </tr>
      </tbody>
    </table>
    <p v-else>No contacts found.</p>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'ContactList',
  data() {
    return {
      contacts: [],
      loading: true,
      error: null,
    };
  },
  mounted() {
    axios.get('http://localhost:5000/contacts')
      .then(response => {
        this.contacts = response.data.contacts; // adapt this based on your backend
      })
      .catch(error => {
        this.error = "Failed to load contacts.";
        console.error(error);
      })
      .finally(() => {
        this.loading = false;
      });
  }
}
</script>
