// frontend/src/components/AddContact.vue
<template>
  <div>
    <h2>Add Contact</h2>
    <form @submit.prevent="addContact">
      <input v-model="name" placeholder="Name" required />
      <input v-model="phone" placeholder="Phone" required />
      <input v-model="email" placeholder="Email" />
      <button type="submit">Add</button>
    </form>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      name: '',
      phone: '',
      email: '',
    };
  },
  methods: {
    async addContact() {
      const user_id = localStorage.getItem('user_id');
      if (!user_id) {
        alert('User not logged in');
        return;
      }

      try {
        const response = await axios.post('http://localhost:5000/contacts', {
          name: this.name,
          phone: this.phone,
          email: this.email,
          user_id: user_id
        });
        alert('Contact added successfully');
        this.name = '';
        this.phone = '';
        this.email = '';
      } catch (error) {
        console.error("Add contact error:", error);
        alert('Failed to add contact');
      }
    }
  }
};
</script>

// frontend/src/components/AddContact.jsx
import React, { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';

const AddContact = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    user_id: localStorage.getItem('user_id')
  });
  const navigate = useNavigate();

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await axios.post('http://localhost:5000/contacts', formData, {
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${localStorage.getItem('token')}`
        }
      });
      navigate('/contacts');
    } catch (error) {
      console.error('Error adding contact:', error);
    }
  };

  return (
    <div className="add-contact-container">
      <h2>Add New Contact</h2>
      <form onSubmit={handleSubmit}>
        <div className="form-group">
          <label>Name:</label>
          <input
            type="text"
            name="name"
            value={formData.name}
            onChange={handleChange}
            required
          />
        </div>
        <div className="form-group">
          <label>Email:</label>
          <input
            type="email"
            name="email"
            value={formData.email}
            onChange={handleChange}
            required
          />
        </div>
        <div className="form-group">
          <label>Phone:</label>
          <input
            type="tel"
            name="phone"
            value={formData.phone}
            onChange={handleChange}
            required
          />
        </div>
        <button type="submit">Add Contact</button>
      </form>
    </div>
  );
};

export default AddContact;
