// frontend/src/components/Register.vue
<template>
  <div class="register">
    <h2>Register</h2>
    <form @submit.prevent="registerUser" enctype="multipart/form-data">
      <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" v-model="name" required />
      </div>
      <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" v-model="email" required />
      </div>
      <div class="form-group">
        <label for="phone">Phone Number:</label>
        <input type="tel" v-model="phone" required />
      </div>
      <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" v-model="password" required />
      </div>
      <div class="form-group">
        <label for="confirmPassword">Confirm Password:</label>
        <input type="password" v-model="confirmPassword" required />
      </div>
      <div class="form-group">
        <label for="profilePic">Profile Picture:</label>
        <input type="file" @change="handleFileChange" accept="image/*" />
        <div v-if="previewUrl" class="preview-container">
          <img :src="previewUrl" alt="Profile Preview" class="preview-image" />
        </div>
      </div>
      <div class="form-group">
        <button type="submit">Register</button>
      </div>
      <p>Already have an account? <router-link to="/login">Login</router-link></p>
    </form>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      name: '',
      email: '',
      phone: '',
      password: '',
      confirmPassword: '',
      profilePic: null,
      previewUrl: null
    };
  },
  methods: {
    handleFileChange(event) {
      const file = event.target.files[0];
      if (file) {
        this.profilePic = file;
        this.previewUrl = URL.createObjectURL(file);
      }
    },
    async registerUser() {
      if (this.password !== this.confirmPassword) {
        alert('Passwords do not match!');
        return;
      }

      try {
        const formData = new FormData();
        formData.append('name', this.name);
        formData.append('email', this.email);
        formData.append('phone', this.phone);
        formData.append('password', this.password);
        if (this.profilePic) {
          formData.append('profile_pic', this.profilePic);
        }

        console.log('Sending registration data:', {
          name: this.name,
          email: this.email,
          phone: this.phone,
          hasProfilePic: !!this.profilePic
        });

        const response = await axios.post('http://localhost:5000/register', formData, {
          headers: {
            'Content-Type': 'multipart/form-data'
          }
        });

        console.log('Registration successful:', response.data);
        alert('Registration successful! Please login.');
        this.$router.push('/login');
      } catch (error) {
        console.error('Registration failed:', error);
        const errorMessage = error.response?.data?.error || 'Registration failed. Please try again.';
        alert(errorMessage);
      }
    }
  }
};
</script>

<style scoped>
.register {
  max-width: 400px;
  margin: 40px auto;
  padding: 20px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

h2 {
  text-align: center;
  color: #333;
  margin-bottom: 20px;
}

.form-group {
  margin-bottom: 15px;
}

label {
  display: block;
  margin-bottom: 5px;
  color: #555;
}

input {
  width: 100%;
  padding: 8px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 16px;
}

input:focus {
  outline: none;
  border-color: #ff5e62;
}

button {
  width: 100%;
  padding: 10px;
  background: #ff5e62;
  color: white;
  border: none;
  border-radius: 4px;
  font-size: 16px;
  cursor: pointer;
  transition: background 0.3s;
}

button:hover {
  background: #ff4448;
}

.preview-container {
  margin-top: 10px;
  text-align: center;
}

.preview-image {
  max-width: 150px;
  max-height: 150px;
  border-radius: 50%;
  object-fit: cover;
  border: 2px solid #ff5e62;
}

p {
  text-align: center;
  margin-top: 15px;
}

a {
  color: #ff5e62;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}
</style>

// frontend/src/components/Register.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import './Register.css';

const Register = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    confirmPassword: '',
    phone: '',
    photo: null
  });
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [passwordError, setPasswordError] = useState('');
  const [emailError, setEmailError] = useState('');
  const [nameError, setNameError] = useState('');
  const [phoneError, setPhoneError] = useState('');
  const navigate = useNavigate();

  const validatePassword = (password) => {
    const minLength = 8;
    const hasUpperCase = /[A-Z]/.test(password);
    const hasLowerCase = /[a-z]/.test(password);
    const hasNumber = /\d/.test(password);
    const hasSpecialChar = /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/.test(password);
    
    if (password.length < minLength) {
      return 'Password must be at least 8 characters long';
    }
    if (!hasUpperCase) {
      return 'Password must contain at least one uppercase letter';
    }
    if (!hasLowerCase) {
      return 'Password must contain at least one lowercase letter';
    }
    if (!hasNumber) {
      return 'Password must contain at least one number';
    }
    if (!hasSpecialChar) {
      return 'Password must contain at least one special character';
    }
    
    return '';
  };

  const validateEmail = (email) => {
    const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
    return emailRegex.test(email) ? '' : 'Please enter a valid email address';
  };

  const validateName = (name) => {
    if (name.length > 55) {
      return 'Name cannot exceed 55 characters';
    }
    return '';
  };

  const validatePhone = (phone) => {
    if (!phone) return ''; 
    
    
    const digitsOnly = phone.replace(/\D/g, '');
    
    if (digitsOnly.length !== 10) {
      return 'Phone number must contain exactly 10 digits';
    }
    return '';
  };

  const handleChange = (e) => {
    const { name, value, files } = e.target;
    if (name === 'photo') {
      setFormData({ ...formData, photo: files[0] });
    } else {
      setFormData({ ...formData, [name]: value });
    }
    
    if (name === 'password') {
      setPasswordError(validatePassword(value));
    }

    if (name === 'email') {
      setEmailError(validateEmail(value));
    }

    if (name === 'name') {
      setNameError(validateName(value));
    }

    if (name === 'phone') {
      setPhoneError(validatePhone(value));
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setSuccess('');
    
   
    const nameValidationError = validateName(formData.name);
    if (nameValidationError) {
      setNameError(nameValidationError);
      return;
    }
    
    
    const emailValidationError = validateEmail(formData.email);
    if (emailValidationError) {
      setEmailError(emailValidationError);
      return;
    }
    
    
    const passwordValidationError = validatePassword(formData.password);
    if (passwordValidationError) {
      setPasswordError(passwordValidationError);
      return;
    }
    
    
    if (formData.phone) {
      const phoneValidationError = validatePhone(formData.phone);
      if (phoneValidationError) {
        setPhoneError(phoneValidationError);
        return;
      }
    }
    
    if (formData.password !== formData.confirmPassword) {
      setError('Passwords do not match');
      return;
    }
    try {
      const data = new FormData();
      data.append('name', formData.name);
      data.append('email', formData.email);
      data.append('password', formData.password);
      data.append('phone', formData.phone);
      if (formData.photo) {
        data.append('profile_pic', formData.photo);
      }
      await axios.post('http://localhost:5000/register', data);
      setSuccess('Registration successful! You can now log in.');
      setTimeout(() => navigate('/'), 1500);
    } catch (err) {
      setError(err.response?.data?.error || 'Registration failed');
    }
  };

  return (
    <div className="register-container">
      <h2>Register</h2>
      {error && <div className="error-message">{error}</div>}
      {success && <div className="success-message">{success}</div>}
      <form onSubmit={handleSubmit} encType="multipart/form-data">
        <div className="form-group">
          <label>Name:</label>
          <input 
            type="text" 
            name="name" 
            value={formData.name} 
            onChange={handleChange} 
            maxLength={55}
            required 
          />
          {nameError && <div className="name-error">{nameError}</div>}
          <div className="char-counter">{formData.name.length}/55 characters</div>
        </div>
        <div className="form-group">
          <label>Email:</label>
          <input type="email" name="email" value={formData.email} onChange={handleChange} required />
          {emailError && <div className="email-error">{emailError}</div>}
        </div>
        <div className="form-group">
          <label>Password:</label>
          <input type="password" name="password" value={formData.password} onChange={handleChange} required />
          {passwordError && <div className="password-error">{passwordError}</div>}
          <div className="password-requirements">
            Password must contain at least 8 characters with one uppercase letter, one lowercase letter, one number, and one special character.
          </div>
        </div>
        <div className="form-group">
          <label>Confirm Password:</label>
          <input type="password" name="confirmPassword" value={formData.confirmPassword} onChange={handleChange} required />
        </div>
        <div className="form-group">
          <label>Phone:</label>
          <input 
            type="tel" 
            name="phone" 
            value={formData.phone} 
            onChange={handleChange}
            placeholder="Enter 10-digit phone number" 
          />
          {phoneError && <div className="phone-error">{phoneError}</div>}
          <div className="phone-requirements">
            Phone number must contain exactly 10 digits.
          </div>
        </div>
        <div className="form-group">
          <label>Photo:</label>
          <input type="file" name="photo" accept="image/*" onChange={handleChange} />
        </div>
        <button type="submit" disabled={!!passwordError || !!emailError || !!nameError || !!phoneError}>Register</button>
      </form>
      <p>
        Already have an account?{' '}
        <span className="link" onClick={() => navigate('/')}>Login here</span>
      </p>
    </div>
  );
};

export default Register;
