// contact-management-react/src/components/ContactList.jsx
import React, { useEffect, useState } from 'react';
import axios from 'axios';

function ContactList() {
  const [contacts, setContacts] = useState([]);
  const user_id = localStorage.getItem('user_id');

  useEffect(() => {
    const fetchContacts = async () => {
      try {
        const res = await axios.get(`http://localhost:5000/contacts?user_id=${user_id}`);
        setContacts(res.data);
      } catch (err) {
        console.error('Failed to fetch contacts:', err);
      }
    };

    if (user_id) fetchContacts();
  }, [user_id]);

  const handleDelete = async (id) => {
    try {
      await axios.delete(`http://localhost:5000/contacts/${id}`);
      setContacts(prev => prev.filter(contact => contact.id !== id));
    } catch (err) {
      console.error('Failed to delete contact:', err);
    }
  };

  return (
    <div>
      <h2>Your Contacts</h2>
      <ul>
        {contacts.map(contact => (
          <li key={contact.id}>
            {contact.name} - {contact.phone} - {contact.email}
            <button onClick={() => handleDelete(contact.id)}>Delete</button>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default ContactList;

// RapidRise-2025-FrontEnd-Assignment/frontend/src/components/ContactList.vue
<template>
  <div>
    <h2>Your Contacts</h2>
    <div v-if="contacts.length === 0">No contacts found.</div>
    <ul>
      <li v-for="contact in contacts" :key="contact.id">
        <strong>{{ contact.name }}</strong> – {{ contact.phone }} – {{ contact.email }}
      </li>
    </ul>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      contacts: [],  
    };
  },
  mounted() {
    this.fetchContacts();  
  },
  methods: {
    async fetchContacts() {
      const user_id = localStorage.getItem('user_id');
      if (!user_id) {
        alert("Please log in");
        return;
      }

      try {
        const response = await axios.get(`http://localhost:5000/contacts?user_id=${user_id}`);
        this.contacts = response.data;  
      } catch (error) {
        console.error("Error fetching contacts:", error);
      }
    }
  }
};
</script>
