// frontend/src/components/ViewContacts.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';

const ViewContacts = () => {
  const [contacts, setContacts] = useState([]);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  useEffect(() => {
    fetchContacts();
  }, []);

  const fetchContacts = async () => {
    try {
      const response = await axios.get('http://localhost:5000/contacts', {
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${localStorage.getItem('token')}`
        }
      });
      const userContacts = response.data.filter(
        contact => contact.user_id === parseInt(localStorage.getItem('user_id'))
      );
      setContacts(userContacts);
    } catch (error) {
      setError('Failed to fetch contacts');
    }
  };

  const handleEdit = (contactId) => {
    navigate(`/edit-contact/${contactId}`);
  };

  const handleDelete = async (contactId) => {
    try {
      await axios.delete(`http://localhost:5000/contacts/${contactId}`, {
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${localStorage.getItem('token')}`
        }
      });
      fetchContacts();
    } catch (error) {
      setError('Failed to delete contact');
    }
  };

  return (
    <div className="contacts-page">
      <div className="contacts-header">
        <h1>My Contacts</h1>
        <button className="add-contact-btn" onClick={() => navigate('/add-contact')}>
          Add New Contact
        </button>
      </div>
      {error && <div className="error-message">{error}</div>}
      <div className="contacts-list">
        {contacts.length === 0 ? (
          <p className="no-contacts">No contacts found. Add your first contact!</p>
        ) : (
          contacts.map(contact => (
            <div key={contact.id} className="contact-card">
              <h3>{contact.name}</h3>
              <p>Email: {contact.email}</p>
              <p>Phone: {contact.phone}</p>
              <div className="contact-actions">
                <button onClick={() => handleEdit(contact.id)}>Edit</button>
                <button onClick={() => handleDelete(contact.id)}>Delete</button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};

export default ViewContacts;

// RapidRise-2025-FrontEnd-Assignment/frontend/src/components/ViewContacts.vue
<template>
  <div>
    <h2>Your Contacts</h2>
    <div v-if="contacts.length === 0">No contacts found.</div>
    <ul>
      <li v-for="contact in contacts" :key="contact.id">
        <strong>{{ contact.name }}</strong> – {{ contact.phone }} – {{ contact.email }}
        <button @click="editContact(contact)">Update</button>
        <button @click="deleteContact(contact.id)">Delete</button>
      </li>
    </ul>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      contacts: []
    };
  },
  async mounted() {
    const user_id = localStorage.getItem('user_id');
    if (!user_id) {
      alert("Please log in");
      this.$router.push("/login");
      return;
    }

    try {
      const response = await axios.get('http://localhost:5000/contacts');
      const allContacts = response.data;
      this.contacts = allContacts.filter(contact => String(contact.user_id) === user_id);
    } catch (error) {
      console.error("Error fetching contacts:", error);
    }
  },
  methods: {
    async deleteContact(contactId) {
      try {
        await axios.delete(`http://localhost:5000/contacts/${contactId}`);
        this.contacts = this.contacts.filter(contact => contact.id !== contactId);
        alert("Contact deleted successfully");
      } catch (error) {
        console.error("Error deleting contact:", error);
        alert("Failed to delete contact");
      }
    },
    editContact(contact) {
      console.log("Saving contact to localStorage:", contact); 
      localStorage.setItem('edit_contact', JSON.stringify(contact));
      this.$router.push('/edit-contact');
    }
  }
};
</script>
