// frontend/src/App.vue
<template>
  <div id="app">
    <nav>
      <ul>
        <li><router-link to="/login">Login</router-link></li>
        <li><router-link to="/register">Register</router-link></li>
        <li><router-link to="/addcontact">Add Contact</router-link></li>
      </ul>
    </nav>

    <router-view></router-view>  <!-- This will display the current route's component -->
  </div>
</template>

<script>
export default {
  name: 'App'
}
</script>

// contact-management-react/src/App.jsx
// src/App.js
import React from 'react';
import Register from './components/Register';
import Login from './components/Login';
import AddContact from './components/AddContact';

function App() {
  return (
    <div>
      <h1>React Contact Management</h1>
      <Register />
      <Login />
      <AddContact />
    </div>
  );
}

export default App;
